# Generated by Django 5.0 on 2024-01-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_list', '0002_tag_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(max_length=255),
        ),
    ]
